version: '3.8'

services:
  aidbox-server:
    build: .
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MCP_HTTP_MODE=true
      - AIDBOX_URL=${AIDBOX_URL}
      - AIDBOX_CLIENT_ID=${AIDBOX_CLIENT_ID}
      - AIDBOX_CLIENT_SECRET=${AIDBOX_CLIENT_SECRET}
    volumes:
      - aidbox_logs:/app/logs
    restart: unless-stopped

volumes:
  aidbox_logs: